modLoader="javafml"
loaderVersion="[4,)"
license="MIT"
issueTrackerURL="https://github.com/Zmotive/CreateSmartDeployTorches/issues"

[[mods]]
modId="create_sdt"
version="1.0.0"
displayName="Create: Smart Deploy Torches"
authors="Zack Tokarczyk"
description='''A Create addon that adds smart deployment capabilities for torches based on light levels.'''

[[dependencies.create_sdt]]
modId="neoforge"
type="required"
versionRange="[21.1,)"
ordering="NONE"
side="BOTH"

[[dependencies.create_sdt]]
modId="minecraft"
type="required"
versionRange="[1.21.1,)"
ordering="NONE"
side="BOTH"

[[dependencies.create_sdt]]
modId="create"
type="required"
versionRange="[6.0,)"
ordering="AFTER"
side="BOTH"
